import { getAppData, setAppData } from './appData'
import { FIELD_CHECKLIST_OVERRIDES_KEY, isEmptyOverrides } from './fieldChecklistOverrides'

// { [jobNumber]: { overrides: {...}, extra: [...] } }. One blob, same
// reason the owner/category/detail maps are one blob: the Worker has no
// list endpoint, so per-job keys could not be read back without already
// knowing every job number.
export async function fetchFieldChecklistOverrides() {
  const raw = await getAppData(FIELD_CHECKLIST_OVERRIDES_KEY)
  return raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {}
}

function entryFor(current, jobNumber) {
  const existing = current[String(jobNumber)]
  return { overrides: { ...(existing?.overrides ?? {}) }, extra: [...(existing?.extra ?? [])] }
}

function withEntry(current, jobNumber, entry) {
  const next = { ...current }
  const id = String(jobNumber)
  // Clearing the last thing customized on a job removes its entry entirely,
  // the same rule jobDetailsStore.js follows — the stored blob stays the
  // set of jobs that actually have something on them.
  if (isEmptyOverrides(entry)) delete next[id]
  else next[id] = entry
  return next
}

// Reword one task for one job. An empty label clears the override — the
// task falls back to the template's own wording, not to a blank string.
// Returns the map actually saved, or null if the write did not reach the
// server, so a text box never keeps showing wording that was never stored.
export async function saveTaskLabelOverride(jobNumber, taskId, label) {
  const current = await fetchFieldChecklistOverrides()
  const entry = entryFor(current, jobNumber)
  const text = String(label ?? '').trim()

  if (text) entry.overrides[taskId] = text
  else delete entry.overrides[taskId]

  const next = withEntry(current, jobNumber, entry)
  const ok = await setAppData(FIELD_CHECKLIST_OVERRIDES_KEY, next)
  return ok ? next : null
}

// Add a job-specific task, ahead of the crew reaching site. `id` is
// generated by the caller — see ProjectDetail.jsx — so an optimistic render
// and the stored row carry the same one and a later edit or removal doesn't
// need a round trip first to learn what id was assigned.
export async function saveExtraTask(jobNumber, task) {
  const current = await fetchFieldChecklistOverrides()
  const entry = entryFor(current, jobNumber)
  const withoutExisting = entry.extra.filter((t) => t.id !== task.id)
  entry.extra = [...withoutExisting, { id: task.id, label: String(task.label ?? '').trim() }]

  const next = withEntry(current, jobNumber, entry)
  const ok = await setAppData(FIELD_CHECKLIST_OVERRIDES_KEY, next)
  return ok ? next : null
}

// Only an office-added extra task can be removed here — see the matching
// rule on the field-app side for site-added ones. An id that isn't in this
// job's own `extra` list (because it's a template task or a site-added one)
// is silently a no-op rather than an error: the caller only ever offers a
// Remove button next to a row it fetched from here in the first place.
export async function removeExtraTask(jobNumber, id) {
  const current = await fetchFieldChecklistOverrides()
  const entry = entryFor(current, jobNumber)
  entry.extra = entry.extra.filter((t) => t.id !== id)

  const next = withEntry(current, jobNumber, entry)
  const ok = await setAppData(FIELD_CHECKLIST_OVERRIDES_KEY, next)
  return ok ? next : null
}
